cookie:
  expiry_days: 30
  key: random_key
  name: auth_cookie
credentials:
  usernames:
    janedoe:
      name: Jane Doe
      password: $2b$12$0QUbRHdgeYNBEmvAyReWPuoAaExl4n7CD1VoN2fqp5GJszSQyMJD.
    johndoe:
      name: John Doe
      password: $2b$12$W0oqzL5LjhXlmL8Qhmcir.HluV1RxoXiiwSoCpAJKNJI80KCu4ane
preauthorized:
  emails: []
